version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend/
    volumes:
      - static:/app/frontend_static
    command: cp -r /app/build/. /app/frontend_static

  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
      - frontend
    volumes:
      - static:/app/web/
      - media:/app/media/

  nginx:
    build: ./infra/
    env_file: .env
    volumes:
      - static:/web
      - media:/web/media
    ports:
      - 7777:80