# Generated by Django 3.2 on 2024-07-22 20:12

import django.core.validators
from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+\\Z'), recipes.validators.username_validator], verbose_name='Юзернейм'),
        ),
    ]
